name: MOVE

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd server
          npm i
          npx sequelize-cli db:migrate
          pm2 restart
          cd ..
          cd client
          npm i
          npm run build
          sudo service nginx reload
